#allows the system to use the date and random strings

import random
import datetime

#list of all possible prophecies it can choose from

prophecies = [
"seek the truth and you will find but ensure you always stay wise" , "You will hear laughter, but no one else will be laughing",
"The object you’ve lost will find you before you find it",
"A stranger will speak your truth before you even know it",
"The storm you dread will pass—but not before it knocks twice",
"You will see your reflection in a place it doesn’t belong",
"The day you wear old shoes will lead to new steps",
"A broken thing will work when it is needed most",
"You’ll forget something important, but only because you’re meant to",
"Someone will hum your favorite song before you say a word",
"A question you ask in jest will be answered in seriousness",
"Beware the moment of perfect silence—it’s never empty",
"You will meet someone twice—once as a stranger, once as a sign", "A new beginning will rise when you least expect it",
"The path you walk will lead to a door only you can open",
"A piece of your past will come to guide your future",
"The shadows you fear today will be the light you carry tomorrow",
"The key to your dreams is hidden in the choices you hesitate to make",
"A step forward will take you further than you realize",
"The heart you’ve given will return to you tenfold",
"The winds of change are stirring, but they blow in your favor",
"You are meant to leave a mark, even if you don’t see it yet",
"What seems like a setback will be the push you need",
"You will find wealth not in gold, but in the moments you treasure",
"A friend you have yet to meet will become your greatest ally",
"The stars align in ways you cannot yet understand",
"A quiet thought will lead to a loud action",
"The past does not define you, but it will guide you",
"Your journey will be long, but it will always be forward",
"The choice you’re about to make will bring peace to your soul",
"A new opportunity will arrive just when you think none exist",
"Your dreams are not as far as they seem",
"A simple gesture will open doors you never knew existed",
"The answers you seek are buried within your own heart",
"The world you’re meant to create is waiting for you to begin",
"Every ending marks the start of something greater",
"Your light will shine brightest when you embrace your darkness",
"The one you least expect will show you the way",
"A moment of doubt will lead to a breakthrough",
"You will find what you seek, but not where you expected",
"An old friend will return to help you in ways you can't foresee",
"You will rise higher than you ever imagined, but only through patience",
"The time you’ve been waiting for is already here",
"What you’ve lost will return to you, but in a form you’ve never known",
"The power to change your life is within your reach, if you dare to grasp it",
"You are closer to success than you think",
"Your greatest strength lies in your ability to remain calm",
"The love you seek is closer than you realize",
"The path will be hard, but it will lead to great rewards",
"You will soon discover your true purpose",
"When you let go of fear, the universe will open its arms",
"An unexpected change will turn out to be the best thing that ever happened to you",
"A new bond will form in the most unlikely place",
"The challenges you face will make you stronger than you ever knew",
"Your spirit is more powerful than you give it credit for",
"A breakthrough will come at the moment you stop searching for it",
"Your mind is the most powerful tool you possess",
"You will meet someone who will change your life forever",
"The thing you fear most will not be as terrible as it seems",
"Soon, the pieces of your life will fall into place",
"A surprise awaits you just around the corner",
"The more you give, the more you will receive",
"Your courage will inspire others to find their own",
"A deep inner peace is coming, just beyond the horizon",
"The end of one chapter will open the most exciting one yet",
"Your hard work will pay off, and the reward will exceed your expectations",
"The answers you seek lie within the quiet moments",
"You will find a way even when none seems possible",
"An unexpected encounter will alter the course of your future",
"Trust your instincts—they are leading you exactly where you need to go",
"You are destined for greatness, but it will come with time",
"A new passion will ignite in you when you least expect it",
"The patience you practice now will lead to great rewards",
"You will soon meet someone who will help you realize your true potential",
"The future you dream of is being shaped by your actions today",
"A new perspective will bring clarity to your deepest questions",
"A simple decision will have a profound impact on your future",
"The truth you seek is hidden in plain sight",
"A shift in your mindset will unlock doors you didn’t know existed",
"The choices you make today will echo through the years",
"A long-anticipated change will arrive at the perfect moment",
"You are on the brink of a discovery that will change everything",
"What you’ve been waiting for will arrive when you stop looking for it",
"A gift of knowledge will soon be placed in your hands",
"The love you give will return to you in surprising ways",
"Your future holds a place of peace, even if it feels distant now",
"Soon, you will know exactly what path to take",
"A change in direction will lead you to the life you’ve always imagined",
"A quiet whisper will soon lead to a loud revelation",
"The answers you’ve been seeking are within your reach",
"Soon, you will discover a strength within you that you never knew existed",
"A shift in your heart will lead to a shift in your life",
"What you desire is already on its way to you",
"The person you are meant to become is closer than you think",
"You will find your greatest joy in the least expected places",
"The wisdom you seek will arrive when you open your heart to it",
"You are about to step into a new chapter of growth and transformation",
"You will soon find peace in a place you’ve never thought to look",
"A powerful force is guiding you toward your destiny",
"You will find success in ways you never imagined possible",
"The storm is over, and the sun will shine brighter than before",
"A familiar voice will carry a message you didn’t know you needed",
"You will soon find clarity in what once confused you",
"An unexpected delay will lead to an unforeseen opportunity",
"Kindness shown today will echo for years to come",
"Your silence will speak louder than words",
"A distant memory will become a guiding light",
"Your greatest strength lies in what you’ve yet to discover",
"What you build now will outlast your own time",
"A chance encounter will shift your path forever",
"Truth will come wrapped in patience",
"An empty hand will soon hold something priceless",
"The courage to ask will lead to answers long hidden",
"Someone is watching your progress with quiet admiration",
"A locked door in your life will soon open",
"The next sunrise will bring you more than light",
"You will teach others without even realizing it",
"What you forgive will free you",
"The words you need to hear will come from a stranger",
"Your effort is being seen, even if not yet rewarded",
"A forgotten place will reveal a new beginning",
"Your patience is planting seeds you’ll soon harvest",
"A mirror will show you more than your reflection",
"You will soon speak words that change everything",
"A small kindness will return to you as a great blessing",
"Something hidden will make itself known",
"You will recognize the truth by how it makes you feel",
"The future is already unfolding in your favor",
"A quiet moment will change your loudest doubts",
"Your feet are already walking toward your purpose",
"You will rise from what tried to bury you",
"A gift will arrive disguised as a problem",
"What you thought was the end is just a pause",
"A long walk will reveal a short answer",
"Someone is waiting for your story to begin",
"Your name will be spoken in gratitude by someone you don’t know",
"What you thought you lost will find its way back",
"You will find strength in the place you avoided",
"The next risk you take will reward your heart",
"An old fear will melt under new light",
"A question you’ve feared will bring healing once asked",
"You will stumble into something meant for you",
"Your ideas are the sparks of something great",
"You’re being prepared for something greater than expected",
"A simple truth will unlock a complex mystery",
"You are on someone’s mind for all the right reasons",
"The smallest decision today will shift your tomorrow",
"Your story is just beginning to unfold",
"A quiet apology will bring loud peace",
"The peace you seek is within reach",
"An old dream will come back with new purpose",
"You will overcome what once overwhelmed you",
"An unopened letter will carry an answer",
"You will leave behind more light than you take",
"The things you don’t say are still shaping your life",
"You will see the impact you’ve had on others",
"A season of rest will come just when it’s needed",
"You will find peace where you once found pain",
"An unseen ally is clearing your path",
"Something you create will outlive you",
"The next turn you take will be the right one",
"You are becoming the person you once needed",
"A routine day will bring an extraordinary moment",
"Your intuition will guide you safely",
"You will be the calm in someone else’s storm",
"What is meant for you is moving closer",
"You will be known for something beautiful",
"A secret hope will soon take form",
"What once confused you will suddenly make sense",
"The patience you’ve practiced will pay off",
"A goodbye will open space for something new",
"The answer you seek will come in a dream",
"You will touch more lives than you ever realize",
"An unexpected change will bring deep relief",
"What you’re building will stand for years to come",
"A single step will set everything in motion",
"You are about to walk into your next chapter",
"Your kindness will be returned tenfold",
"Someone needs your words more than you know",
"An old lesson will help you solve something new",
"You will find joy where you forgot to look",
"A familiar song will carry a message",
"What’s ending is clearing space for better things",
"Your presence brings comfort in silence",
"Someone admires you quietly from afar",
"A door you thought was closed will open soon",
"Your voice carries power, even in whispers",
"You will find balance in the chaos",
"A path will reveal itself when you stop searching",
"You’re about to discover what truly matters",
"The next time you hesitate, leap instead",
"Your light will guide someone through darkness",
"What felt like a mistake will become your strength",
"You will hear news that brings peace",
"A shared smile will lead to something meaningful",
"You’re not lost, you’re being guided",
"You will soon understand why it all had to happen",
"The energy you give will return brighter",
"A hidden talent will surface at the perfect moment",
"What breaks your heart will open your spirit",
"A whisper in the quiet will carry the truth",
"The fate will find you when the storm passes",
"The ally will change on a day like any other",
"The wish will guide you beneath the surface",
"The wind is coming under the quiet moon",
"The door will arrive in the moment between thoughts",
"The coin will return when you're ready",
"The step will shift under the quiet moon",
"The mirror will guide you in the moment between thoughts",
"The hope will carry beneath the surface",
"The storm will change beneath the surface",
"The memory will find you when you're ready",
"The mirror will show itself when you least expect it",
"The step will heal with a heavy heart",
"The glimpse is coming in the moment between thoughts",
"The sky will echo as the silence deepens",
"The star will inspire on a day like any other",
"The truth will shift beneath the surface",
"The storm will carry in the moment between thoughts",
"The wish will inspire as the silence deepens",
"The breath will shift in the moment between thoughts",
"The river will find you in the hands of another",
"The star will carry on a day like any other",
"The spark will shift under the quiet moon",
"The spark will return when you're ready",
"The fire will reveal on a day like any other",
"The signal will heal when you're ready",
"The wind will guide you when you're ready",
"The star will find you while you're looking away",
"The storm will change with a heavy heart",
"The memory is coming as the silence deepens",
"The spark will carry as the silence deepens",
"The hope will echo when you least expect it",
"The truth will lead you under the quiet moon",
"The signal will return when the storm passes",
"The fire will heal before the next sunrise",
"The echo will show itself without needing to be asked",
"The sky will reveal while you're looking away",
"The memory is coming while you're looking away",
"The key will return under the quiet moon",
"The truth is waiting as the silence deepens",
"The mirror will teach without needing to be asked",
"The light will reveal before the next sunrise",
"The strength will guide you beneath the surface",
"The season will bless while you're looking away",
"The silence will inspire when the storm passes",
"The dream will bless on a day like any other",
"The memory will return through the words of a friend",
"The thread will shape when you least expect it",
"The door will carry through the words of a friend",
"The echo will teach as the stars align",
"The echo will arrive without needing to be asked",
"The dream will arrive when you're ready",
"The sign will bless when the storm passes",
"The dream will shift when you least expect it",
"The dream will inspire when you're ready",
"The memory will shift when you're ready",
"The strength is coming when the storm passes",
"The strength will unfold without needing to be asked",
"The memory will reveal beneath the surface",
"The wish will change before the next sunrise",
"The wish will heal while you're looking away",
"The memory is waiting without needing to be asked",
"The thread will arrive as the stars align",
"The light will inspire through the words of a friend",
"The ally will carry beneath the surface",
"The fire will guide you before the next sunrise",
"The memory will unfold while you're looking away",
"The silence will arrive as the silence deepens",
"The key will teach when you least expect it",
"The journey will carry when you least expect it",
"The wish is coming with a heavy heart",
"The key will carry in the hands of another",
"The step will carry before the next sunrise",
"The key will return through the words of a friend",
"The coin will heal under the quiet moon",
"The memory will change as the stars align",
"The path will carry as the silence deepens",
"The fire is waiting as the silence deepens",
"The thread will reveal while you're looking away",
"The key will shift on a day like any other",
"The light will lead you in the hands of another",
"The sky will unfold in the hands of another",
"The wish will change through the words of a friend",
"The shadow will test through the words of a friend",
"The step is coming through the words of a friend",
"The echo will test beneath the surface",
"The storm will reveal when you least expect it",
"The seed will shape in the moment between thoughts",
"The thread will return under the quiet moon",
"The ally will return as the stars align",
"The question will lead you with a heavy heart",
"The storm will change in the moment between thoughts",
"The storm will unfold as the silence deepens",
"The journey will show itself beneath the surface",
"The river will return in the moment between thoughts",
"The wind is waiting before the next sunrise",
"The sign will reveal on a day like any other",
"The name will find you under the quiet moon",
"The mirror will lead you in the hands of another",
"The light will teach while you're looking away",
"The mirror will bless on a day like any other",
"The key will guide you when you're ready",
"The coin will arrive on a day like any other",
"The river will shift when the storm passes",
"The star will shift while you're looking away",
"The wind will shift when you're ready",
"The echo will return as the stars align",
"The name will return beneath the surface",
"The name will guide you on a day like any other",
"The wish will find you before the next sunrise",
"The river will inspire beneath the surface",
"The journey will teach as the silence deepens",
"The voice will test through the words of a friend",
"The season will change on a day like any other",
"The time will echo as the silence deepens",
"The mirror will unfold when the storm passes",
"The wish will inspire without needing to be asked",
"The coin will unfold before the next sunrise",
"The storm will reveal beneath the surface",
"The fire will find you as the stars align",
"The season will find you while you're looking away",
"The fire will return in the moment between thoughts",
"The spark will reveal in the moment between thoughts",
"The voice will test before the next sunrise",
"The echo is waiting under the quiet moon",
"The hope will bless on a day like any other",
"The star will heal while you're looking away",
"The ally is waiting beneath the surface",
"The spark will guide you when you least expect it",
"The ally will return when you're ready",
"The sky is coming in the moment between thoughts",
"The storm will carry without needing to be asked",
"The step will return as the stars align",
"The name will inspire while you're looking away",
"The wind will teach as the silence deepens",
"The silence will test on a day like any other",
"The sign is waiting while you're looking away",
"The sky will test in the hands of another",
"The ally will echo when you're ready",
"The question will bless when you're ready",
"The breath will arrive with a heavy heart",
"The glimpse will lead you beneath the surface",
"The river will heal in the moment between thoughts",
"The sky will shift when you least expect it",
"The signal will heal with a heavy heart",
"The echo will carry when the storm passes",
"The hope will inspire in the hands of another",
"The fate will heal in the hands of another",
"The time will find you as the stars align",
"The answer will unfold on a day like any other",
"The time will inspire before the next sunrise",
"The coin will unfold as the silence deepens",
"The path will reveal through the words of a friend",
"The door will guide you beneath the surface",
"The silence will heal on a day like any other",
"The seed will reveal before the next sunrise",
"The answer will shift in the hands of another",
"The answer will reveal in the moment between thoughts",
"The door will change on a day like any other",
"The door will unfold when you least expect it",
"The star is waiting through the words of a friend",
"The fate will reveal in the moment between thoughts",
"The gift will unfold when the storm passes",
"The shadow will guide you as the silence deepens",
"The fire will carry while you're looking away",
"The breath will teach when you least expect it",
"The voice will bless through the words of a friend",
"The season will bless before the next sunrise",
"The mirror is coming through the words of a friend",
"The truth will lead you while you're looking away",
"The shadow will test in the moment between thoughts",
"The mirror will shift as the silence deepens",
"The key will test without needing to be asked",
"The answer will shift while you're looking away",
"The question is coming on a day like any other",
"The door will show itself beneath the surface",
"The silence will show itself beneath the surface",
"The mirror will echo through the words of a friend",
"The thread will teach in the moment between thoughts",
"The spark will teach in the moment between thoughts",
"The river will reveal when you least expect it",
"The key will bless beneath the surface",
"The star will echo in the hands of another",
"The breath will bless when you're ready",
"The gift will shape when you're ready",
"The wind will inspire as the stars align",
"The thread will lead you as the stars align",
"The dream will teach while you're looking away",
"The journey will lead you on a day like any other",
"The fate will shape on a day like any other",
"The storm will echo as the silence deepens",
"The time will unfold when the storm passes",
"The seed will reveal when you're ready",
"The answer will shape when you're ready",
"The journey will change as the stars align",
"The voice will change without needing to be asked",
"The river will heal beneath the surface",
"The hope will heal through the words of a friend",
"The name will change in the moment between thoughts",
"The thread will change as the silence deepens",
"The coin will unfold while you're looking away",
"The breath will carry before the next sunrise",
"The dream will lead you under the quiet moon",
"The shadow will lead you beneath the surface",
"The question will find you on a day like any other",
"The coin will bless when the storm passes",
"The answer will test when the storm passes",
"The fate will bless in the moment between thoughts",
"The season will unfold in the moment between thoughts",
"The truth will test when the storm passes",
"The door will shape through the words of a friend",
"The river will heal without needing to be asked",
"The step will heal before the next sunrise",
"The fire will inspire with a heavy heart",
"The hope will inspire while you're looking away",
"The river will lead you as the stars align",
"The name will carry through the words of a friend",
"The signal will return as the silence deepens",
"The glimpse will shift as the stars align",
"The voice will guide you when you least expect it",
"The breath is coming when the storm passes",
"The path will shape on a day like any other",
"The thread will inspire as the silence deepens",
"The dream will test in the hands of another",
"The time will test while you're looking away",
"The gift will reveal under the quiet moon",
"The dream will show itself through the words of a friend",
"The glimpse will arrive when the storm passes",
"The breath will guide you with a heavy heart",
"The voice will heal on a day like any other",
"The question will carry with a heavy heart",
"The storm will change beneath the surface",
"The gift will carry through the words of a friend",
"The season will heal without needing to be asked",
"The coin will guide you with a heavy heart",
"The answer will teach when you're ready",
"The fire will return when you least expect it",
"The fire will echo when you're ready",
"The door will shift in the hands of another",
"The breath will inspire beneath the surface",
"The flame will shape as the silence deepens",
"The sign will shape when the storm passes",
"The spark will return as the stars align",
"The path will heal without needing to be asked",
"The river will arrive in the hands of another",
"The river will find you on a day like any other",
"The storm will carry in the moment between thoughts",
"The memory is coming when the storm passes",
"The journey will return in the hands of another",
"The truth will find you while you're looking away",
"The wind will lead you while you're looking away",
"The silence will show itself with a heavy heart",
"The silence will echo with a heavy heart",
"The voice will show itself when you're ready",
"The ally will inspire through the words of a friend",
"The key is coming as the silence deepens",
"The river will show itself in the moment between thoughts",
"The breath will unfold without needing to be asked",
"The mirror will test before the next sunrise",
"The glimpse will show itself beneath the surface",
"The glimpse will arrive when you're ready",
"The light will teach under the quiet moon",
"The journey will echo as the silence deepens",
"The shadow will shape with a heavy heart",
"The signal will echo beneath the surface",
"The thread will test without needing to be asked",
"The time will teach with a heavy heart",
"The glimpse will bless as the stars align",
"The step will find you when you least expect it",
"The wish will test when the storm passes",
"The mirror will shift before the next sunrise",
"The dream will inspire before the next sunrise",
"The season will heal in the hands of another",
"The star will return in the moment between thoughts",
"The seed will shape beneath the surface",
"The name will teach as the silence deepens",
"The truth will carry when you least expect it",
"The sky will lead you in the hands of another",
"The gift will arrive as the silence deepens",
"The hope is coming under the quiet moon",
"The sky will arrive through the words of a friend",
"The step will return as the stars align",
"The time will inspire as the silence deepens",
"The breath will echo in the hands of another",
"The spark will unfold without needing to be asked",
"The mirror will teach as the silence deepens",
"The question will show itself as the stars align",
"The sign will test as the stars align",
"The strength is coming when the storm passes",
"The journey will test beneath the surface",
"The time will inspire when you're ready",
"The journey will heal on a day like any other",
"The hope will reveal with a heavy heart",
"The thread will shift in the hands of another",
"The season will show itself without needing to be asked",
"The hope will carry as the silence deepens",
"The truth will heal in the moment between thoughts",
"The flame will teach under the quiet moon",
"The thread will lead you when you're ready",
"The key will inspire without needing to be asked",
"The question will teach when the storm passes",
"The memory is waiting before the next sunrise",
"The wind will show itself under the quiet moon",
"The light is coming when you're ready",
"The step will heal with a heavy heart",
"The echo will teach without needing to be asked",
"The fire will return beneath the surface",
"The door will teach as the silence deepens",
"The journey will shift as the silence deepens",
"The ally will inspire when you least expect it",
"The thread will show itself beneath the surface",
"The gift will return in the hands of another",
"The memory will lead you on a day like any other",
"The dream will change in the moment between thoughts",
"The name will heal with a heavy heart",
"The mirror is waiting when you least expect it",
"The hope will find you under the quiet moon",
"The breath will return beneath the surface",
"The journey will reveal when the storm passes",
"The path will guide you under the quiet moon",
"The season will heal beneath the surface",
"The strength will teach in the moment between thoughts",
"The answer will echo with a heavy heart",
"The answer will reveal when you least expect it",
"The answer will inspire under the quiet moon",
"The breath is waiting without needing to be asked",
"The glimpse will change in the moment between thoughts",
"The name will shift as the stars align",
"The wind will arrive before the next sunrise",
"The silence will bless with a heavy heart",
"The question will inspire while you're looking away",
"The thread will shift under the quiet moon",
"The star will guide you when the storm passes",
"The path will bless when the storm passes",
"The breath will arrive as the silence deepens",
"The memory will test while you're looking away",
"The thread will guide you before the next sunrise",
"The light will carry before the next sunrise",
"The gift will lead you when you least expect it",
"The coin will arrive as the silence deepens",
"The river will guide you before the next sunrise",
"The river will shift in the hands of another",
"The spark is coming before the next sunrise",
"The storm is waiting as the silence deepens",
"The season will find you when you're ready",
"The breath will shift as the silence deepens",
"The truth is waiting with a heavy heart",
"The river will test as the silence deepens",
"The spark will change with a heavy heart",
"The key will bless with a heavy heart",
"The key will find you when you least expect it",
"The journey will heal before the next sunrise",
"The star will arrive when you least expect it",
"The truth will unfold beneath the surface",
"The star will find you with a heavy heart",
"The journey will return when the storm passes",
"The silence will carry as the stars align",
"The mirror will shift when you least expect it",
"The sign will arrive as the silence deepens",
"The dream will echo in the moment between thoughts",
"The mirror will lead you as the stars align",
"The dream will return under the quiet moon",
"The gift will reveal before the next sunrise",
"The season will find you as the silence deepens",
"The river will inspire when you least expect it",
"The seed will echo when you least expect it",
"The echo will test as the silence deepens",
"The breath will shape when you least expect it",
"The fate will echo when the storm passes",
"The season will find you as the stars align",
"The signal will inspire through the words of a friend",
"The memory will echo when the storm passes",
"The path will echo while you're looking away",
"The seed will return through the words of a friend",
"The door will heal before the next sunrise",
"The shadow will return in the hands of another",
"The signal will lead you while you're looking away",
"The wish will test without needing to be asked",
"The fate will bless while you're looking away",
"The fire is coming in the hands of another",
"The echo will lead you with a heavy heart",
"The shadow will echo when you're ready",
"The sky will reveal in the moment between thoughts",
"The time will return when the storm passes",
"The glimpse will reveal in the hands of another",
"The sign will shift when you least expect it",
"The answer will unfold in the moment between thoughts",
"The fate will show itself on a day like any other",
"The echo will arrive when you least expect it",
"The silence will bless as the silence deepens",
"The time will return through the words of a friend",
"The question will inspire in the moment between thoughts",
"The dream will test when you're ready",
"The wish will echo through the words of a friend",
"The light will show itself when you're ready",
"The sky will reveal under the quiet moon",
"The truth will change beneath the surface",
"The star will echo through the words of a friend",
"The echo will find you while you're looking away",
"The spark will carry on a day like any other",
"The question will bless in the moment between thoughts",
"The wind will inspire as the stars align",
"The star will carry in the hands of another",
"The strength is coming in the hands of another",
"The truth will lead you when the storm passes",
"The path will reveal before the next sunrise",
"The gift is waiting in the hands of another",
"The seed will arrive in the moment between thoughts",
"The gift will find you while you're looking away",
"The fate will echo on a day like any other",
"The silence will arrive on a day like any other",
"The key will guide you as the silence deepens",
"The seed will change when the storm passes",
"The fate is coming when the storm passes",
"The storm is coming beneath the surface",
"The storm will change on a day like any other",
"The light will guide you before the next sunrise",
"The flame will arrive when you're ready",
"The memory will teach as the silence deepens",
"The thread will find you through the words of a friend",
"The thread will arrive without needing to be asked",
"The fire will teach through the words of a friend",
"The echo will return on a day like any other",
"The fire will show itself under the quiet moon",
"The journey will heal before the next sunrise",
"The key will unfold when the storm passes",
"The step will heal with a heavy heart",
"The shadow will find you beneath the surface",
"The sky will return through the words of a friend",
"The time will reveal when the storm passes",
"The key will find you through the words of a friend",
"The mirror will return as the stars align",
"The echo will inspire as the stars align",
"The answer will return as the silence deepens",
"The sky will find you when you're ready",
"The key will show itself under the quiet moon",
"The gift will heal while you're looking away",
"The sky will heal as the silence deepens",
"The coin will echo before the next sunrise",
"The spark will return without needing to be asked",
"The hope will arrive as the silence deepens",
"The silence is waiting beneath the surface",
"The thread will change in the hands of another",
"The breath will guide you when you're ready",
"The key will echo on a day like any other",
"The voice will show itself without needing to be asked",
"The shadow is waiting under the quiet moon",
"The fire will show itself through the words of a friend",
"The path will show itself in the moment between thoughts",
"The sky will shift through the words of a friend",
"The river will echo in the moment between thoughts",
"The key will heal when you least expect it",
"The ally will change through the words of a friend",
"The step will shift in the moment between thoughts",
"The fate will test under the quiet moon",
"The wind will shift as the stars align",
"The journey will lead you with a heavy heart",
"The sign will inspire on a day like any other",
"The spark will arrive while you're looking away",
"The light is waiting as the stars align",
"The river is coming beneath the surface",
"The question will find you without needing to be asked",
"The gift will bless beneath the surface",
"The path will bless in the hands of another",
"The sky will guide you when the storm passes",
"The star will show itself when the storm passes",
"The river will lead you beneath the surface",
"The light will arrive under the quiet moon",
"The silence will arrive through the words of a friend",
"The storm is waiting while you're looking away",
"The season will reveal under the quiet moon",
"The flame will bless on a day like any other",
"The seed will inspire without needing to be asked",
"The dream will reveal while you're looking away",
"The question will unfold on a day like any other",
"The dream will show itself under the quiet moon",
"The star will lead you on a day like any other",
"The echo will test as the stars align",
"The mirror will arrive while you're looking away",
"The dream is coming beneath the surface",
"The fire will unfold under the quiet moon",
"The sign is coming with a heavy heart",
"The thread is coming in the moment between thoughts",
"The truth is waiting in the moment between thoughts",
"The hope is coming as the stars align",
"The name will unfold when you least expect it",
"The time will carry without needing to be asked",
"The light will return when the storm passes",
"The dream will shift when you least expect it",
"The door will unfold when the storm passes",
"The door will lead you as the silence deepens",
"The storm will change on a day like any other",
"The thread will lead you as the stars align",
"The echo will shift under the quiet moon",
"The key will arrive through the words of a friend",
"The flame will guide you on a day like any other",
"The shadow will unfold while you're looking away",
"The hope will shape with a heavy heart",
"The key will guide you when the storm passes",
"The storm will teach as the stars align",
"The path will lead you in the hands of another",
"The wind will teach in the moment between thoughts",
"The fire will lead you in the hands of another",
"The answer will return with a heavy heart",
"The spark will carry in the moment between thoughts",
"The name will guide you when you're ready",
"The sign will find you when you least expect it",
"The storm is coming when you least expect it",
"The wind will test beneath the surface",
"The question will test in the moment between thoughts",
"The light will bless beneath the surface",
"The gift will shape through the words of a friend",
"The step will lead you when you least expect it",
"The hope will lead you as the silence deepens",
"The voice will shape beneath the surface",
"The strength will bless before the next sunrise",
"The mirror will heal on a day like any other",
"The question will shift when you least expect it",
"The star will lead you in the hands of another",
"The memory will echo when you least expect it",
"The light will guide you in the moment between thoughts",
"The gift will unfold beneath the surface",
"The wind will change in the moment between thoughts",
"The sign will echo as the stars align",
"The echo will reveal with a heavy heart",
"The strength will return before the next sunrise",
"The echo will lead you through the words of a friend",
"The answer will reveal under the quiet moon",
"The hope will return when you least expect it",
"The light will reveal beneath the surface",
"The river will arrive when you're ready",
"The shadow will change through the words of a friend",
"The question will unfold in the hands of another",
"The gift is waiting with a heavy heart",
"The wind will teach in the moment between thoughts",
"The step will shift under the quiet moon",
"The season will change in the hands of another",
"The memory will unfold on a day like any other",
"The light will echo without needing to be asked",
"The light will heal with a heavy heart",
"The wish will test as the stars align",
"The ally will find you when the storm passes",
"The name is coming in the moment between thoughts",
"The hope will lead you through the words of a friend",
"The path will lead you as the stars align",
"The flame is coming on a day like any other",
"The key will find you as the stars align",
"The flame will lead you before the next sunrise",
"The storm will carry in the moment between thoughts",
"The truth will show itself on a day like any other",
"The season is coming through the words of a friend",
"The voice will bless when you're ready",
"The sign will heal before the next sunrise",
"The name is coming when the storm passes",
"The river will arrive when you least expect it",
"The question will heal before the next sunrise",
"The strength will bless when you're ready",
"The dream will find you while you're looking away",
"The path will change with a heavy heart",
"The truth will carry beneath the surface",
"The spark will change in the moment between thoughts",
"The river will heal with a heavy heart",
"The silence will bless without needing to be asked",
"The hope will guide you in the hands of another",
"The silence will shape on a day like any other",
"The seed will bless when you're ready",
"The name will return on a day like any other",
"The flame will show itself when the storm passes",
"The journey will arrive beneath the surface",
"The voice will guide you while you're looking away",
"The river will carry when you're ready",
"The mirror will unfold as the silence deepens",
"The journey will reveal when the storm passes",
"The fate will unfold in the hands of another",
"The answer will show itself on a day like any other",
"The name will shift in the moment between thoughts",
"The time will bless beneath the surface",
"The light will test without needing to be asked",
"The voice will test when you least expect it",
"The key will guide you while you're looking away",
"The name will test when you least expect it",
"The spark will carry in the hands of another",
"The ally will inspire while you're looking away",
"The dream is coming when you least expect it",
"The strength is waiting through the words of a friend",
"The flame will arrive before the next sunrise",
"The truth will shift without needing to be asked",
"The echo will find you with a heavy heart",
"The silence will return when you're ready",
"The strength will bless when you least expect it",
"The time will arrive without needing to be asked",
"The thread will shift while you're looking away",
"The spark will test when you least expect it",
"The answer will arrive when the storm passes",
"The coin will guide you as the stars align",
"The gift will return in the hands of another",
"The sign is waiting in the moment between thoughts",
"The truth is waiting in the hands of another",
"The season will reveal when the storm passes",
"The sign will find you beneath the surface",
"The name will lead you on a day like any other",
"The name will inspire when you least expect it",
"The season will find you beneath the surface",
"The step will unfold before the next sunrise",
"The sky will shift as the silence deepens",
"The strength will return in the moment between thoughts",
"The wind is coming beneath the surface",
"The light will reveal under the quiet moon",
]

#MAIN MENU
while True:
    print("👋 welcome to what's your destiny 🔮 ")
    print("----------------------------------------------------------------")
    print("What would you like to do?")
    print("1. Uncover your destiny ✨🔮 ")
    print("2. Quit ")
    choice = input("What's your choice? ").strip()

    if choice == '1':
        chosen_prophecy = random.choice(prophecies)
        today = datetime.date.today()
        print(f"Your prophecy for {today.strftime('%B')} {today.day}:")
        print(chosen_prophecy)
    elif choice == '2':
        print("Goodbye traveller 👋")
        break
    else:
        print("Please choose a valid option.")
#picks a random one by refrencing the list and choosing a random one each time


#Makes date and time a variable so i can reference when need
# {today.strftime('%B')}
#Formats todays date to show the name of the current month
#today.day shows todays day number dynamically
#so that it can be used every day of the year


